pull_request_rules:
  - name: label conflicts
    conditions:
      - conflict
    actions:
      label:
        toggle:
          - conflict

  - name: Automatic merge on approval
    conditions:
      - '#commits-behind=0'
      - or:
          - '#approved-reviews-by>=1'
          - label=ci:auto-merge
      - or:
          - not:
              and:
                - 'head*=renovate/lockfile-maintenance-*'
          - 'created-at<=24h ago'
      - base=master
      - check-success=cargo-fmt
      - check-success=all-ci-jobs
    actions:
      merge:
        method: squash
