from typing import Any

def bencode(v: Any, /) -> bytes: ...
def bdecode(b: bytes, decode_keys: list[bytes] | None = None, /) -> Any: ...

class BencodeEncodeError(Exception): ...
class BencodeDecodeError(Exception): ...
