name: Build Wheels

on:
  push:
    branches:
      - master
    tags-ignore:
      - "*"

jobs:
  build:
    concurrency:
      group: "${{ github.workflow }}-${{ github.ref }}"
      cancel-in-progress: true
    uses: ./.github/workflows/_build_wheels.yaml

  audit:
    name: Audit
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install abi3audit

      - uses: actions/download-artifact@v4
        with:
          name: wheel
          path: dist

      - run: abi3audit --verbose dist/*.whl
